name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  packages:
    runs-on: ubuntu-latest

    permissions:
      # Needed for PyPI trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # setuptools_scm needs the tags

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python -m build
          twine check --strict dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
